sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: orders_id
            description: No Primary key of the table
            tests:
              - not_null
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - not_null
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: products of greenweez
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - not_null
              - unique
      - name: adwords
        identifier: raw_gz_adwords
        description: Ads of Adwords
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        description: Ads of Bing
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        description: Ads of Criteo
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        description: Ads of Facebook
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: int_campaigns
        description: data from all campaigns
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name:
                - paid_source
                - campaign_name
    